name: Call Remotion-Matrix-Renderer
run-name: Render ${{ github.event.inputs.identifier }}
on:
  workflow_dispatch:
    inputs:
      scale:
        description: 'Scale'
        type: string
        default: "1"
        required: true
      identifier:
        description: 'Identifier'
        type: string
        required: false
      props:
        description: Video Props
        required: true
        default: |
          {
          "musicTitle": "Everything goes on - Porter Robinson",
          "syncronizeLyrics": [],
          "background": {
            "video": "https://static.moewalls.com/videos/preview/2022/star-guardian-akali-and-kaisa-league-of-legends-preview.mp4"
          },
          "ytmMusicInfo": "",
          "ytmThumbnail": "",
          "searchLyricsIndex": 0
          }
jobs:
  call-workflow-in-another-repo:
    uses: FightFarewellFearless/Remotion-Matrix-Renderer/.github/workflows/render-video-matrix.yml@master
    with:
      num_of_workers: 5
      remotion_composition_id: MusicLyrics
      remotion_entry_point: src/index.ts
      props: ${{ github.event.inputs.props }}
      scale: ${{ github.event.inputs.scale }}
      id: ${{ github.event.inputs.identifier }}
