# This is a basic workflow that is manually triggered

name: Render Video

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      props:
        description: Video Props
        required: true
        default: |
          {
            musicTitle: "Tampar - Juicy Luicy",
            syncronizeLyrics: [],
            background: {
              video: "https://static.moewalls.com/videos/preview/2023/rain-drops-blurry-city-preview.mp4"
            },
            ytmMusicInfo: '',
            ytmThumbnail: '',
            searchLyricsIndex: 0,
          }

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  render:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@main
    - name: Install dependencies
      run: npm install 
      # && sudo apt update -y && sudo apt install -y libnss3 libdbus-1-3 libatk1.0-0 libasound2 libxrandr2 libxkbcommon-dev libxfixes3 libxcomposite1 libxdamage1 libgbm-dev libatk-bridge2.0-0
    - uses: FedericoCarboni/setup-ffmpeg@v3
    - name: Create out folder
      run: mkdir out
      env:
          WORKFLOW_INPUT: ${{ github.event.inputs.props }}
    - name: creating thumbnail
      run: npx remotion still MusicThumbnail out/lyrics.png --props="$(echo $WORKFLOW_INPUT)"
    - name: rendering...
      run: npx remotion render MusicLyrics out/lyrics.mp4 --props="$(echo $WORKFLOW_INPUT)"
    - name: Upload Video
      uses: actions/upload-artifact@v4
      with:
        name: video-rendering-result
        path: out/*


